#ifndef QBASE_CHAINPARAMSSEEDS_H
#define QBASE_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the qbase network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {NULL, NULL}
};

static SeedSpec6 pnSeed6_test[] = {
    {NULL, NULL}
};
#endif // QBASE_CHAINPARAMSSEEDS_H
